.TH KSMBD.ADDUSER "8" "October 2021" "Usage: smbuseradd" "Linux System Administration"
.SH NAME
ksmbd.adduser \- Adds, updates or removes (-a/-u/-d) a user from ksmbd pwd file.
.SH SYNOPSIS
.B ksmbd.adduser

.SH DESCRIPTION
.HP
\fB\-a\fR | \fB\-\-add\-user\fR=\fI\,login\/\fR
.HP
\fB\-d\fR | \fB\-\-del\-user\fR=\fI\,login\/\fR
.HP
\fB\-u\fR | \fB\-\-update\-user\fR=\fI\,login\/\fR
.HP
\fB\-p\fR | \fB\-\-password\fR=\fI\,pass\/\fR
.HP
\fB\-i\fR smbpwd.db | \fB\-\-import\-users\fR=\fI\,smbpwd\/\fR.db
.HP
\fB\-V\fR | \fB\-\-version\fR
.HP
\fB\-v\fR | \fB\-\-verbose\fR
