.TH KSMBD.MOUNTD "8" "October 2021" "ksmbd-tools version : 3.3.9" "Linux System Administration"
.SH NAME
ksmbd.mountd \- manual page for ksmbd-tools version : 3.3.9
.SH SYNOPSIS
.B ksmbd.mountd

.SH DESCRIPTION
.TP
\fB\-\-p\fR=\fI\,NUM\/\fR | \fB\-\-port\fR=\fI\,NUM\/\fR
TCP port NUM
.TP
\fB\-\-c\fR=\fI\,smb\/\fR.conf | \fB\-\-config\fR=\fI\,smb\/\fR.conf
config file
.TP
\fB\-\-u\fR=\fI\,pwd\/\fR.db | \fB\-\-users\fR=\fI\,pwd\/\fR.db
Users DB
.TP
\fB\-\-n\fR | \fB\-\-nodetach\fR
Don't detach
.TP
\fB\-\-s\fR | \fB\-\-systemd\fR
Service mode
.TP
\fB\-V\fR | \fB\-\-version\fR
Show version
.TP
\fB\-h\fR | \fB\-\-help\fR
Show help
